# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Telephony-ErlangC
version:      0.03
version_from: lib/Math/Telephony/ErlangC.pm
installdirs:  site
requires:
    Math::Telephony::ErlangB:      0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
